nptscot/nptscot.github.io

- js/layer_control.js
> Switch rnets

- js/layer_control.js
This reverts commit b968401f85d3d7f6f3610bdea4bbc17c2a55112e.
Closes #57
> Revert "Switch rnets"

- manual/index.html
> 104 rewrite of manual for launch

- js/layer_control.js
@Robinlovelace, can you check the new AADT results? This PR can run locally to see new results while GitHub site is still on old version
> Switch to AADT

- index.html
- manual/index.html
- Add descriptive text in chart text div
- Replace TEXT HERE placeholder with contents, close #121
> 121 remove text here bit

- css/main.css
- index.html
- src/nptui.js
- src/settings.js
This set of changes implements URL state (layers enabled and map position) as per #147, by addition of a hash. E.g.:
#/rnet-simplified,wards,holyrood/#11.52/55.9659/-2.9368
Further work to implement parameters within each layer will follow.
> Implement URL state

- index.html
- src/datasets.js
- src/nptui.js
> 154 cohesive colourscheme

- manual/index.md
Moving Accessing NPT section to bottom of page as it feels least important.
> Moved_Accessing_NPT_section.md

- manual/index.md
> hyperlink_CycleByDesign.md

- index.html
- src/datasets.js
Implement colour scheme for CLoS - main sublayer only
Refs #175
> 175 Implement colour scheme for CLoS - main sublayer only

- index.html
- src/datasets.js
- **First pass at updated colours for new infrastructure labels**
- **Update colourscheme**
> 205 add road type field to most datasets to aid rendering 1

- src/datasets.js
Reverts nptscot/nptscot.github.io#210
> Revert "Starter on #209, new data"

- index.html
- src/datasets.js
> Reorder street space categories

- src/nptui.js
Fixes #234.
@Robinlovelace Ready for review and merge.
> 234 placenames

- .gitignore
- css/manual.css
- data/index.html
- index.html
- js/localauthorities.js
- localauthorities/index.html
- manual/index.html
- src/settings.js
@Robinlovelace Adds the new tab. Ready for review and merging.
> Add local authorities tab with links to scheme sketcher; refs #245

- index.html
- manual/index.md
> Add coherent network section to manual/help; fixes #169

- css/main.css
- index.html
- src/nptui.js
Now fixed, was just an edge-case timing issue. I've forced this to load when the map is ready now, as that should guarantee controls are present.
> Fix geolocation tooltip; fixes #229

- index.html
- manual/index.md
- src/datasets.js
> Fix people cycling per day -> cycle trips per day; fixes #261

- index.html
- src/datasets.js
- **Try new style for Traffic volume category field**
- **Update traffic volume field name, close #267**
> 267 update cbd layer with new data

- index.html
- src/datasets.js
- **Add new cn, working**
- **Primary link colour working!**
- **Working with colours**
- **Add new cn legend, close #282**
> 282 update core network layer 1

- src/datasets.js
> Disable schools chart auto-popups

- src/nptui.js
A couple of changes which got stuck in the layers work but are not germane to it, and which I am now decluttering.
> Side panel cleanups

- index.html
- src/datasets.js
This is working but I'm working on a less wordy style definition. I suggest merging straight away, pending a better change.
> Street space: Style support (multi-layers)

- src/datasets.js
- src/nptui.js
Better implementation now for #302, ready for merging.
> Add macro to auto-expand sublayers with same styling, to avoid repetitive definitions

- index.html
Fixes #310 without needing wider changes.
> Tighten labels to avoid panel overflow; fixes #310

- index.html
> 305 infrastructure streetview

- index.html
- src/datasets.js
- **Fix streetspace dropdown typo**
- **Update Absolute min colour, differentiate from not enough space**
- **Add popups, close #318**
- **tidy up**
> 318 update streetspace ui

- index.html
- manual/index.md
- **update street space manual**
- **update the format**
> update street space

- index.html
- src/nptui.js
- src/settings.js
Reverts nptscot/nptscot.github.io#322
> Revert "Load build file"

- manual/index.md
- **fix number bus lane display**
- **update width definition**
> 329 number of bus lanes data not displaying correctly in streetspace popup

- staticwebapp.config.json
I **think** this should work, but I can't test without creating a pile of Azure infrastructure.
This needs to be merged to the live site to fix the problem noted there.
It will have no effect on the Github-hosted site.
> Add staticwebapp.config file; fixes #334

- css/main.css
- index.html
> 328 streetspace popups

- css/main.css
Fixes #328 (further objective).
> 328 popups styling

- index.html
- src/datasets.js
NB please leave the branch open after merging.
> Add bus routes; fixes #371

- index.html
- **Another go at #375**
- **Format nicely**
> 375 update description of street space layer in ui

- index.html
- src/datasets.js
> Add urban/rural boundary layer; fixes #370

- css/main.css
- index.html
- manual/index.md
> Fix street space evaluation text; fixes #382

- index.html
- **udpate the pop up**
- **remobe no of bus lane**
> 386 change fields in street space pop up

- src/datasets.js
> LoS: Adjust medium to be less bright yellow more orange; fixes #363

- index.html
Fix speed limit label; fixes #399
> Fix speed limit label; fixes #399

- src/datasets.js
> Existing network: add 'Should not be used' category; fixes #388

- src/datasets.js
> Speed limits: Update colour scheme; fixes #364

- css/main.css
- index.html
- src/datasets.js
- src/nptui.js
See #408.
This commit does not change any behaviour, other than filling in a few legends that were missing, but it substantially refactors various aspects of layer definition and how legends are generated.
> 408 unify layers

- src/datasets.js
> 411 407 speed limit colours

- src/datasets.js
Fixes #362. Images in that issue.
> Clos: Style line widths by highway type, and value by colour; fixes #362

- index.html
- src/datasets.js
- src/nptui.js
Further layer refactorings, to tidy up inconsistencies and make definitions further more self-explanatory.
> Layer refactorings

- src/datasets.js
This commit replaces 674fe978590e26b5ac0da0135b4f51d1d02bb91d which is now obsoleted by the reworked style definition structure code - that original change would not merge now.
> Traffic volumes: Add new 1k point (revised commit); fixes #391

- src/datasets.js
Reverts nptscot/nptscot.github.io#420
> Revert "update using post overline funs"

- src/nptui.js
> Fix map movement on hash change; fixes #425

- js/manual.js
- manual/index.md
> 448 manual hyperlinks

- about/index.html
- css/main.css
- data/index.html
- index.html
- localauthorities/index.html
- manual/index.html
- privacy/index.html
- src/nptui.js
> Beta button and updated text; fixes #464

- index.html
- src/nptui.js
> fix(docs): hardcode date in landing page popup

- src/settings.js
- **Update to show all of scotland**
- **Tweak landing page, more zoomed-out**
> 475 update landing page to show all of scotland

- index.html
Thanks for adding the logo! Please link here, though
> Point to correct A/B Street site

- about/index.html
- data/index.html
- index.html
- localauthorities/index.html
- manual/index.html
> Rename overly long NPW menu label; fixes #501
